### ISSUE TITLE
back port to C++17/20?

### ISSUE THREAD

**Issue by Ravenwater** [Colliflower/png-reader#1]
@Colliflower any plans to backport this to C++17/20?

I am working on Universal, https://github.com/stillwater-sc/universal, a C++ header-only library for mixed-precision algorithm development and optimization. I am adding a mixed-precision DNN library to Universal and to demonstrate how to use it, it needs a PNG reader/writer. Clearly, I subscribe to the header-only approach to C++ libraries, but Universal is being used by folks that are still stuck with C++17, so I am looking for something that they could experiment with as well.

Otherwise stated, wanted to see what your roadmap for this code is.

**Comment by Colliflower** [comment]
If you're looking for a header only solution an amazing solution for multiple file formats exists in [stb_image.h](https://github.com/nothings/stb).
I don't have any current plans for back porting the code or expanding to image writing in the near future. Eventually expanding support for more chunk types + writing would be good but it probably won't happen any time soon.

**Comment by Ravenwater** [comment]
@Colliflower thank you for the guidance.
